// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: api/goodbye.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Goodbye service

func NewGoodbyeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Goodbye service

type GoodbyeService interface {
	Goodbye(ctx context.Context, in *GoodbyeReq, opts ...client.CallOption) (*GoodbyeRsp, error)
}

type goodbyeService struct {
	c    client.Client
	name string
}

func NewGoodbyeService(name string, c client.Client) GoodbyeService {
	return &goodbyeService{
		c:    c,
		name: name,
	}
}

func (c *goodbyeService) Goodbye(ctx context.Context, in *GoodbyeReq, opts ...client.CallOption) (*GoodbyeRsp, error) {
	req := c.c.NewRequest(c.name, "Goodbye.Goodbye", in)
	out := new(GoodbyeRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Goodbye service

type GoodbyeHandler interface {
	Goodbye(context.Context, *GoodbyeReq, *GoodbyeRsp) error
}

func RegisterGoodbyeHandler(s server.Server, hdlr GoodbyeHandler, opts ...server.HandlerOption) error {
	type goodbye interface {
		Goodbye(ctx context.Context, in *GoodbyeReq, out *GoodbyeRsp) error
	}
	type Goodbye struct {
		goodbye
	}
	h := &goodbyeHandler{hdlr}
	return s.Handle(s.NewHandler(&Goodbye{h}, opts...))
}

type goodbyeHandler struct {
	GoodbyeHandler
}

func (h *goodbyeHandler) Goodbye(ctx context.Context, in *GoodbyeReq, out *GoodbyeRsp) error {
	return h.GoodbyeHandler.Goodbye(ctx, in, out)
}
