// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.5.1
// source: api/goodbye.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GoodbyeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *GoodbyeReq) Reset() {
	*x = GoodbyeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_goodbye_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodbyeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodbyeReq) ProtoMessage() {}

func (x *GoodbyeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_goodbye_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodbyeReq.ProtoReflect.Descriptor instead.
func (*GoodbyeReq) Descriptor() ([]byte, []int) {
	return file_api_goodbye_proto_rawDescGZIP(), []int{0}
}

func (x *GoodbyeReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GoodbyeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *GoodbyeRsp) Reset() {
	*x = GoodbyeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_goodbye_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodbyeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodbyeRsp) ProtoMessage() {}

func (x *GoodbyeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_goodbye_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodbyeRsp.ProtoReflect.Descriptor instead.
func (*GoodbyeRsp) Descriptor() ([]byte, []int) {
	return file_api_goodbye_proto_rawDescGZIP(), []int{1}
}

func (x *GoodbyeRsp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_api_goodbye_proto protoreflect.FileDescriptor

var file_api_goodbye_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x62, 0x79, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x62, 0x79, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0a, 0x47,
	0x6f, 0x6f, 0x64, 0x62, 0x79, 0x65, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x32, 0x30, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x62, 0x79, 0x65, 0x12, 0x25,
	0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x62, 0x79, 0x65, 0x12, 0x0b, 0x2e, 0x47, 0x6f, 0x6f, 0x64,
	0x62, 0x79, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x62, 0x79, 0x65,
	0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_goodbye_proto_rawDescOnce sync.Once
	file_api_goodbye_proto_rawDescData = file_api_goodbye_proto_rawDesc
)

func file_api_goodbye_proto_rawDescGZIP() []byte {
	file_api_goodbye_proto_rawDescOnce.Do(func() {
		file_api_goodbye_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_goodbye_proto_rawDescData)
	})
	return file_api_goodbye_proto_rawDescData
}

var file_api_goodbye_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_goodbye_proto_goTypes = []interface{}{
	(*GoodbyeReq)(nil), // 0: GoodbyeReq
	(*GoodbyeRsp)(nil), // 1: GoodbyeRsp
}
var file_api_goodbye_proto_depIdxs = []int32{
	0, // 0: Goodbye.Goodbye:input_type -> GoodbyeReq
	1, // 1: Goodbye.Goodbye:output_type -> GoodbyeRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_goodbye_proto_init() }
func file_api_goodbye_proto_init() {
	if File_api_goodbye_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_goodbye_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodbyeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_goodbye_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodbyeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_goodbye_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_goodbye_proto_goTypes,
		DependencyIndexes: file_api_goodbye_proto_depIdxs,
		MessageInfos:      file_api_goodbye_proto_msgTypes,
	}.Build()
	File_api_goodbye_proto = out.File
	file_api_goodbye_proto_rawDesc = nil
	file_api_goodbye_proto_goTypes = nil
	file_api_goodbye_proto_depIdxs = nil
}
